version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_APP_NAME=subsidie-radar
      - DB_APP_USER=subsidie-radar
      - DB_APP_PASS=subsidie-radar
    volumes:
      - "./data:/var/data/db"